version: '3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080
    depends_on:
      - db
    links:
      - "db:db"

  db:
    build:
      context: db
    volumes:
      - ./db/data_dump:/var/opt/mssql
